version: '3.0'
services:
  es6:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.8.0'
    container_name: es6
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - 'esdata6:/usr/share/elasticsearch/data'
    ports:
      - '9200:9200'
    networks:
      - esnet
  kibana:
    image: 'docker.elastic.co/kibana/kibana:6.8.0'
    container_name: kibana6
    hostname: kibana
    restart: always
    networks:
      - esnet
    environment:
      - SERVER_NAME=kibana.localhost
      - 'ELASTICSEARCH_URL=http://es6:9200'
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - ELASTIC_PWD=changeme
      - KIBANA_PWD=changeme
    ports:
      - '5601:5601'
    expose:
      - '5601'
    links:
      - es6
    depends_on:
      - es6
volumes:
  esdata6:
    driver: local
networks:
  esnet: null
