version: 2

jobs:
  build:
    working_directory: ~/bookstore-elasticsearch
    docker:
      - image: circleci/ruby:2.5.1-node
        environment:
          PGHOST: localhost
          PGUSER: bookstore-elasticsearch
          RAILS_ENV: test
      - image: postgres:10
        environment:
          POSTGRES_USER: bookstore-elasticsearch
          POSTGRES_PASSWORD: bookstore-elasticsearch
          POSTGRES_DB: bookstore-elasticsearch_test
      - image: docker.elastic.co/elasticsearch/elasticsearch:6.8.0
        environment:
          - cluster.name: bookstore-elasticsearch-test-cluster
          - xpack.security.enabled: false
          - transport.host: localhost
          - network.host: 127.0.0.1
          - http.port: 9200
          - discovery.type: single-node
    steps:
      - checkout

      # Update Node.js and npm
      - run: curl -sSL "https://nodejs.org/dist/v8.16.0/node-v8.16.0-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v8.16.0-linux-x64/bin/node
      - run: curl https://www.npmjs.com/install.sh | sudo bash

      # Check current version of node
      - run: node -v

      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: bookstore-elasticsearch-bundle-{{ checksum "Gemfile.lock" }}

      - type: cache-restore
        name: Restore yarn cache
        key: bookstore-elasticsearch-yarn-{{ checksum "yarn.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      - run: yarn install

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: bookstore-elasticsearch-bundle-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - type: cache-save
        name: Store yarn cache
        key: bookstore-elasticsearch-yarn-{{ checksum "yarn.lock" }}
        paths:
          - ~/.yarn-cache

      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Setup the environment
      - run: cp .env.sample .env

      # Setup the database
      - run: bundle exec rake db:setup

      # Precompile assets
      - run: bundle exec rails assets:precompile

      # Run the tests
      - run: bundle exec rake spec
