version: 2

jobs:
  build:
    working_directory: ~/bookstore
    docker:
      - image: circleci/ruby:2.5.1
        environment:
          PGHOST: localhost
          PGUSER: bookstore
          RAILS_ENV: test
      - image: postgres:9.6
        environment:
          POSTGRES_USER: bookstore
          POSTGRES_DB: bookstore_test
          POSTGRES_PASSWORD: ""
      - image: docker.elastic.co/elasticsearch/elasticsearch:6.8.0
        environment:
          - cluster.name: bookstore-elasticsearch-test-cluster
          - xpack.security.enabled: false
          - transport.host: localhost
          - network.host: 127.0.0.1
          - http.port: 9200
          - discovery.type: single-node
    steps:
      - checkout

      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: bookstore-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: bookstore-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Setup the environment
      - run: cp .env.sample .env

      # Setup the database
      - run: bundle exec rake db:setup

      # Run the tests
      - run: bundle exec rake spec
