version: '3'

volumes:
  assets:
  esdata6:

services:
  web_server:
    image: 453563644279.dkr.ecr.eu-central-1.amazonaws.com/bookstore_elasticsearch/web_server
    volumes:
      - assets:/home/www/bookstore-elasticsearch/public/assets
    environment:
      STATIC_PATH: /home/www/bookstore-elasticsearch/public
    ports:
      - 80:8080
    links:
      - server_app
    logging:
      driver: awslogs
      options:
        awslogs-group: bookstore-elasticsearch-production
        awslogs-region: eu-central-1
        awslogs-stream-prefix: web_server
    healthcheck:
      test: ["CMD-SHELL", "service nginx status || exit 1"]

  server_app:
    image: 453563644279.dkr.ecr.eu-central-1.amazonaws.com/bookstore_elasticsearch/server_app
    command: bundle exec puma -C config/puma.rb
    entrypoint: "./docker-entrypoint.sh"
    ports:
      - 3000
    environment:
      RAILS_ENV: production
      SEKRETS_KEY: STUB
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: bookstore-elasticsearch_production
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      ELASTICSEARCH_URL: 'http://elastic:9200'
    volumes:
      - assets:/home/www/bookstore-elasticsearch_production/public/assets
    links:
      - db
      - elastic
    logging:
      driver: awslogs
      options:
        awslogs-group: bookstore-elasticsearch-production
        awslogs-region: eu-central-1
        awslogs-stream-prefix: server_app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]

  db:
    image: postgres:10
    environment:
      POSTGRES_DB: bookstore-elasticsearch_production
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432
    volumes:
      - /postgres:/var/lib/postgresql/data
    logging:
      driver: awslogs
      options:
        awslogs-group: bookstore-elasticsearch-production
        awslogs-region: eu-central-1
        awslogs-stream-prefix: db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]

  elastic:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.8.0'
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - 'esdata6:/usr/share/elasticsearch/data'
    ports:
      - '9200:9200'
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3